-- contracts/schema.sql — source of truth for the database schema.
-- Verbatim per architecture.md §4. Alembic migrations are generated FROM this
-- file and CI diffs the autogenerated migration graph against it (§12.6).
-- Do not edit a migration to fix drift — fix this file, then regenerate.

CREATE EXTENSION IF NOT EXISTS vector;
CREATE EXTENSION IF NOT EXISTS pgcrypto; -- gen_random_uuid()

-- ─── Corpus ────────────────────────────────────────────────────────────
CREATE TABLE episodes (
  id                BIGSERIAL PRIMARY KEY,
  guest             TEXT        NOT NULL,
  title             TEXT        NOT NULL,
  youtube_url       TEXT,
  video_id          TEXT,
  publish_date      DATE,
  duration_seconds  INTEGER,
  source_path       TEXT        NOT NULL UNIQUE,
  content_hash      TEXT        NOT NULL,
  ingested_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE chunks (
  id             BIGSERIAL PRIMARY KEY,
  episode_id     BIGINT      NOT NULL REFERENCES episodes(id) ON DELETE CASCADE,
  ordinal        INTEGER     NOT NULL,
  text           TEXT        NOT NULL,
  token_count    INTEGER     NOT NULL,
  start_seconds  INTEGER,    -- nearest preceding speaker-turn timestamp; NULL if unparseable
  embedding      vector(768) NOT NULL,
  UNIQUE (episode_id, ordinal)
);

CREATE INDEX chunks_embedding_idx
  ON chunks USING ivfflat (embedding vector_cosine_ops) WITH (lists = 100);
CREATE INDEX chunks_episode_idx ON chunks (episode_id);

-- ─── Conversation ──────────────────────────────────────────────────────
CREATE TABLE sessions (
  id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title            TEXT,
  provider         TEXT        NOT NULL,
  model            TEXT        NOT NULL,
  user_ref         TEXT        NOT NULL DEFAULT 'local',
  -- NULL = every discovered skill is active (the default, back-compat
  -- behavior). A non-NULL array is an explicit allowlist of skill names
  -- for this session only (root CLAUDE.md invariant #4: skills are plain
  -- prompt text, so this can never grant a new tool — see agent/src/
  -- capabilities.ts and agent/src/session.ts's skillsOverride usage).
  enabled_skills   TEXT[],
  created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE messages (
  id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  session_id       UUID        NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
  role             TEXT        NOT NULL CHECK (role IN ('user','assistant','system')),
  content          TEXT        NOT NULL,
  rewritten_query  TEXT,
  trace_id         TEXT        NOT NULL,
  provider         TEXT,
  model            TEXT,
  latency_ms       INTEGER,
  token_in         INTEGER,
  token_out        INTEGER,
  abstained        BOOLEAN     NOT NULL DEFAULT false,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX messages_session_idx ON messages (session_id, created_at);

CREATE TABLE citations (
  id          BIGSERIAL PRIMARY KEY,
  message_id  UUID   NOT NULL REFERENCES messages(id) ON DELETE CASCADE,
  chunk_id    BIGINT NOT NULL REFERENCES chunks(id),
  rank        INTEGER NOT NULL,
  score       REAL    NOT NULL
);

CREATE INDEX citations_message_idx ON citations (message_id);

-- ─── Artifacts ─────────────────────────────────────────────────────────
CREATE TABLE artifacts (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  session_id  UUID NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
  message_id  UUID REFERENCES messages(id) ON DELETE SET NULL,
  kind        TEXT NOT NULL CHECK (kind IN ('markdown','html')),
  title       TEXT,
  content     TEXT NOT NULL,
  sanitized   BOOLEAN NOT NULL DEFAULT false,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ─── Extension proposals ────────────────────────────────────────────────
-- A user-submitted DRAFT for a new agent/.pi/extensions/ entry. Recording a
-- proposal here never makes it live: the agent only ever loads extensions
-- listed by path+sha256+tools in agent/.pi/extensions/manifest.json
-- (agent/src/capabilities.ts, root CLAUDE.md invariant #4), and nothing in
-- this app writes to that file or that directory at runtime. `status` is
-- review bookkeeping for a human maintainer, not a deployment switch —
-- 'approved' still requires someone to copy `code` into a committed file,
-- add the matching manifest.json entry, and pass tools/check_extension_
-- manifest.py before it can ever run.
CREATE TABLE extension_proposals (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title         TEXT        NOT NULL,
  description   TEXT        NOT NULL,
  tool_names    TEXT[]      NOT NULL,
  code          TEXT        NOT NULL,
  sha256        TEXT        NOT NULL, -- of `code`, for a reviewer to paste straight into manifest.json
  status        TEXT        NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','approved','rejected')),
  session_id    UUID        REFERENCES sessions(id) ON DELETE SET NULL,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ─── Operations ────────────────────────────────────────────────────────
CREATE TABLE ingest_runs (
  id             BIGSERIAL PRIMARY KEY,
  started_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  finished_at    TIMESTAMPTZ,
  episode_count  INTEGER,
  chunk_count    INTEGER,
  embed_model    TEXT,
  status         TEXT NOT NULL CHECK (status IN ('running','ok','failed','seeded'))
);
